package com.Blog.Platform.Blog.Util;

import org.springframework.stereotype.Service;

import java.util.Random;

@Service
public class DailyThoughtService {

    private final String[] thoughts = {
            "Life is like code, one wrong assumption and everything breaks",
            "Debugging life is harder than debugging code",
            "Sometimes you need to refactor people, not logic",
            "Your mindset is the real compiler",
            "Clean code, messy desk, calm mind",
            "Life has no undo, code does - use both wisely",
            "Bugs in life don't throw errors, they teach lessons",
            "Growth happens outside the comfort zone, just like learning a new framework",
            "If it works, don't touch it - unless it's your life",
            "Coding teaches patience better than meditation",
            "Every failure is just a failed test case",
            "Life doesn't have documentation, learn by debugging",
            "Overthinking is the infinite loop of life",
            "Consistency beats motivation, in code and in life",
            "Some problems need sleep, not solutions",
            "Your future is built one commit at a time",
            "Silence is sometimes the best console log",
            "Code breaks, people break, growth fixes both",
            "Not all errors are mistakes, some are lessons",
            "Life is async, don't block waiting for results",
            "Be like clean code - simple, readable, honest",
            "Success is just well-handled failures",
            "The best developers Google - the best humans ask for help",
            "Don't compare your chapter 1 to someone's version 10",
            "Progress > perfection",
            "Life needs fewer features and more stability",
            "Refactor habits, not just code",
            "Some days you debug, some days you learn",
            "Hard problems build strong developers",
            "Your value is not defined by one bug",
            "Every expert was once confused",
            "Break big dreams into small functions",
            "Learning never throws 404",
            "Be patient, even the best code compiles slowly",
            "Life has memory leaks too - let go",
            "Stay curious, that's the real superpower",
            "Focus on logic, syntax will follow",
            "You don't need to know everything, just enough to move forward",
            "Calm mind writes better code",
            "Bugs reveal character",
            "Sometimes restarting fixes everything",
            "Life is not production, it's continuous development",
            "Good things take time, just like mastery",
            "Your pace is valid",
            "Failure is feedback, not rejection",
            "Trust the process, not the panic",
            "Coding teaches humility every day",
            "Your journey is unique, don't fork someone else's",
            "Even broken code has potential",
            "Think long-term, code short-term",
            "Life doesn't need optimization, just clarity",
            "Every problem has a root cause",
            "Debug your thoughts, not just your code",
            "Focus is a feature, distractions are bugs",
            "Simple life, clean logic",
            "Don't rush growth, even trees take years",
            "Build skills, results will follow",
            "Your best version is still loading",
            "Sometimes doing nothing is the fix",
            "Errors don't define you, responses do",
            "Life is a sandbox, experiment wisely",
            "Stay soft in a hard world",
            "Not all answers come immediately",
            "You are not behind, you are building",
            "Code changes, principles remain",
            "Growth feels uncomfortable, that's how you know it's working",
            "Every day is a new commit",
            "Learn, break, fix, repeat",
            "Peace is better than perfection",
            "You don't need permission to grow",
            "Life is not a race condition",
            "Trust yourself, you've solved harder bugs",
            "Quiet progress is still progress",
            "One step at a time is still forward",
            "Keep shipping, keep learning",
            "You are more than your output",
            "Clarity is power",
            "Strong foundations create strong futures",
            "Breathe, then debug",
            "Your journey matters",
            "Code your life with intention",
            "Be proud of how far you've compiled",
            "Still learning is a flex",
            "Stay hungry, stay humble",
            "You're doing better than you think",
            "Write less noise and more signal",
            "Version control your habits",
            "Measure twice, deploy once",
            "Readability is a kindness",
            "Small wins compound quietly",
            "Strong APIs start with clear contracts",
            "Delete what no longer serves",
            "A bug report is a map, not an attack",
            "Discipline beats intensity over time",
            "Tests are trust you can run",
            "Respect edge cases, they pay rent",
            "Simplicity scales better than cleverness",
            "Good defaults prevent bad days",
            "Latency in life is often uncertainty",
            "Protect your focus like production data",
            "Write for your future self",
            "Ship improvements, not excuses",
            "Reliability is built in boring moments",
            "Feedback is free performance tuning",
            "Consistency is the best automation",
            "Check assumptions before checking logs",
            "Healthy boundaries prevent system overload",
            "Momentum is made of repeated basics",
            "When in doubt, reduce scope",
            "Clarity first, optimization second",
            "Good architecture starts with good questions",
            "Stability is a feature users notice",
            "Pay technical debt before interest grows",
            "Choose progress that can be sustained",
            "The cleanest fix is often the simplest one"
    };

    public String getRandomThought() {
        Random random = new Random();
        return thoughts[random.nextInt(thoughts.length)];
    }
}
